In [14]:

import numpy as np
a = np.array([1,3,4,5,7])
b = np.array([3,9,5,32,5])
a_mean = np.mean(a)
b_mean = np.mean(b)
m = np.sum((a-a_mean)*(b-b_mean))/np.sum((a-a_mean)**2)#m is slope and c is intercept we are finding prediction and precision or error
c = b_mean-m*a_mean
y_precision = m*a+c
error = np.mean((b-b_mean)**2)
print(a)
print(b)
print(m)
print(c)
print(y_precision)
print(error)
print(a_mean)
print(b_mean)
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(np.square(a))
print(np.sqrt(a))
print(np.median(a))
print(np.mode(a))
print(np.median(a))


[1 3 4 5 7]
[ 3  9  5 32  5]
1.4500000000000002
5.0
[ 6.45  9.35 10.8  12.25 15.15]
116.16000000000001
4.0
10.8
[ 4 12  9 37 12]
[ -2  -6  -1 -27   2]
[  3  27  20 160  35]
[0.33333333 0.33333333 0.8        0.15625    1.4       ]
[ 1  9 16 25 49]
[1.         1.73205081 2.         2.23606798 2.64575131]
4.0


In [6]:
#examp of 1st week\
#Q1
import numpy as np
a = np.arange(1,11)
print(a)
print(np.shape(a))
print(a.dtype)
print(np.size(a))





[ 1  2  3  4  5  6  7  8  9 10]
(10,)
int64
10


In [14]:
#Q2
import numpy as np
a = np.arange(1,10).reshape(3,3)
print(a)
print(a[1,:])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[4 5 6]


In [3]:
#Q3
import numpy as np
a = np.arange(2,12,2)
print(np.sum(a))
print(np.mean(a))
print(np.max(a))
print(np.min(a))


30
6.0
10
2


In [9]:
#Q4
import numpy as np
a = np.arange(0,21)
print(a[0:4])
print(a[16:])
print(a[0:21:2])


[0 1 2 3]
[16 17 18 19 20]
[ 0  2  4  6  8 10 12 14 16 18 20]


In [12]:
#Q5
import numpy as np
a = np.arange(0,9).reshape(3,3)
print(a)
print(a.reshape(1,9))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2 3 4 5 6 7 8]]


In [20]:
#Q6
a = np.array([1,3,3])
b = np.array([4,5,6])
print(np.concatenate((a,b)))

[1 3 3 4 5 6]


In [24]:
#Q7
a = np.random.randint(10,51,(4,4))
print(a)
print(np.sum(a))
print(np.max(a))

[[10 20 18 45]
 [47 23 35 32]
 [29 35 24 17]
 [11 35 39 29]]
449
47


In [31]:
#Q7
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))





[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [34]:
a = np.arange(10,51,10)
print(a)
print(np.sqrt(a))
print(np.log(a))

[10 20 30 40 50]
[3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]
[2.30258509 2.99573227 3.40119738 3.68887945 3.91202301]


In [44]:
a = np.random.randint(1,39,(3,3))
print(a)
print(np.mean(a[0,:]))
print(np.mean(a[1,:]))
print(np.mean(a[2,:]))
print(np.mean(a[:,0]))
print(np.mean(a[:,1]))
print(np.mean(a[:,2]))

[[35 31 18]
 [28 15 34]
 [ 1 23  4]]
28.0
25.666666666666668
9.333333333333334
21.333333333333332
23.0
18.666666666666668


In [51]:
a = np.random.randint(1,101,(100))
print(a)
print(np.linspace(0,1,5))

[ 53  52  77  76  67  14  15 100  33  13  53  57  64  54  60  58  20   6
  13  80  43  91  57  32  83  89  48  52   5  27  68  64   5  98  89  72
  17  88   5  30  71  80  26  33  78  24  33  60  32  97   6  32  79  92
  22  26  64  26  72  56 100  20  87  96  52  64  84  77  11  25  21  65
  42  37  26  81  86  61  65  15  30  35  29  52   7  79  73  41  79  34
   4   1  66  28  90  96   3  34  33  25]
[0.   0.25 0.5  0.75 1.  ]


In [60]:
print(np.identity(3))
print(np.ones((3,3))*7)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[7. 7. 7.]
 [7. 7. 7.]
 [7. 7. 7.]]


In [68]:
a = np.arange(1,10).reshape(3,3)
b = np.arange(10,19).reshape(3,3)
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.transpose(a))
print(np.linalg.det(a))
print(np.linalg.inv(a))

[[11 13 15]
 [17 19 21]
 [23 25 27]]
[[-9 -9 -9]
 [-9 -9 -9]
 [-9 -9 -9]]
[[ 10  22  36]
 [ 52  70  90]
 [112 136 162]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
6.66133814775094e-16
[[-4.50359963e+15  9.00719925e+15 -4.50359963e+15]
 [ 9.00719925e+15 -1.80143985e+16  9.00719925e+15]
 [-4.50359963e+15  9.00719925e+15 -4.50359963e+15]]


In [27]:
import numpy as np
sales_data = np.array([[200, 230, 260],
                       [180, 220, 150],
                       [240, 258, 230]])
print("The Total Sales Data of First 3 Months.\n", sales_data)

# 2 slicing to analyze data in both types in rows and columns
data_row = sales_data.reshape(1, 9)
print("\nThe Sales Data in one Row to analyze horizontally.\n", data_row)
data_column = sales_data.reshape(9, 1)
print("\nThe Sales Data in one Column to analyze vertically.\n", data_column)

# 3 in This we get data from specific part of data like one month's sales or this product's total sales
month_sale = sales_data[1]
print("\nFirst month and its sales as sample.\n", month_sale)
product_sale = sales_data[:, 0]
print("\nThe first product's sales in all months.\n", product_sale)
spec_product = sales_data[2, 2]
print("\nThe specific product as sample.\n", spec_product)

# 4 we are finding fluctuation rate
noise = np.random.randint(-20, 21, size=sales_data.shape)
fluctuation = sales_data + noise
print("\nThe Fluctuated Sales Rate after (Original sales + noise):\n", fluctuation)
random_sales = np.random.randint(150, 250, (4, 3))
print("\nThe random sales generated for future 4 months.\n", random_sales)

# 5 Find sales average, max sales, and min sales
print("\nThe Average sales of 3 months is: ", np.mean(sales_data))
print("\nThe max sales of product in all months is: ", np.max(sales_data))
print("\nThe min sales of product in all months is: ", np.min(sales_data))

# 6 Revenue
product_prices = np.array([10, 20, 30])
total_revenue = sales_data * product_prices
print("\nThe revenue according to product prices: \n", total_revenue)
sum_product = np.sum(total_revenue, axis=0)
print("\nThe Total revenue of products in all months: ")
print("\n\nProduct 1 = ", sum_product[0])
print("\nProduct 2 = ", sum_product[1])
print("\nProduct 3 = ", sum_product[2])

# 7 Check invertible
determinant = np.linalg.det(total_revenue)
print("\nThe Determinant of Total Revenue is\n", determinant)
if np.linalg.det(total_revenue) != 0:
    inverse = np.linalg.inv(total_revenue)
    print("\nInverse of the total revenue is: \n", inverse)
else:
    print("The total revenue matrix is not invertible")


The Total Sales Data of First 3 Months.
  [[200 230 260]
 [180 220 150]
 [240 258 230]]

The Sales Data in one Row to anylze horizontaly.
 [[200 230 260 180 220 150 240 258 230]]

The Sales Data in one Column to anylze vertically.
 [[200]
 [230]
 [260]
 [180]
 [220]
 [150]
 [240]
 [258]
 [230]]

First month and its sales as sample.
 [180 220 150]

The first product sales in all months.
 [200 180 240]

The specific product as sample.
 230

The FLuctuated Sales Rate after (Orignal sales+noice):
 [[193 227 273]
 [195 232 134]
 [251 243 231]]

The random dales generated for future 4 months.
 [[248 241 238]
 [200 171 175]
 [186 227 212]
 [219 197 212]]

The Average sales of 3 months is :  218.66666666666666

The max sales of product in All months is :  260

The min sales of product in All months is :  150

The reviniew accoding tpo product prices : 
 [[2000 4600 7800]
 [1800 4400 4500]
 [2400 5160 6900]]
The Total revinew of products in all months : 
Product 1 =  6200
